### ISSUE TITLE
Wrong dependencies for XTTS when AMD GPU is used

### ISSUE THREAD

**Issue by ostr00000** [SillyTavern/SillyTavern-Launcher#30]
### My OS/Hardware
OS: Linux (Ubuntu 23.10)
GPU: AMD

### Problem description

When installing XTTS, the dependencies are installed using `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`. 
This will install CUDA for only NVIDIA GPU. For AMD GPU this needs to be replaced to `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6`.
(This is based on [interactive command generator](https://pytorch.org/get-started/locally/#start-locally).)

### Fix suggestion

For a `conda` environment `extras`  there is a nice option picker for GPU. I think that this picker should be moved before XTTS installation and there should be `if` based on user response.

**Comment by deffcolony** [comment]
@ostr00000 Please update the scripts with `git pull` 
your request has been added at: https://github.com/SillyTavern/SillyTavern-Launcher/blob/471fb15041ce31a7a2584277c9a9dba3605d7e79/install.sh#L434

**Comment by ostr00000** [comment]
I tested a clean installation. Choice for selecting GPU (or even CPU) works perfect. 
The issue is solved.
