### ISSUE TITLE
start_command error when launching SillyTavern + Extra on Windows

### ISSUE THREAD

**Issue by Greanibak** [SillyTavern/SillyTavern-Launcher#31]
Hello guys,

With SillyTavern 1.11.1 'release' (736223a8), I encountered a bug when launching SillyTavern Extras using launcher.bat, specifically with command 3. The CMD window would open but then end with an error related to the start_command not being defined. I noticed that the SillyTavern launcher.bat was sourcing the modules.txt not from the "SillyTavern-extras" folder but from the SillyTavern root folder. Moreover, even the modules.txt in the SillyTavern folder doesn't seem to work on Windows, as it lacks the "start_command" at the beginning, as well as the server.py. The parsing intended by the code doesn't seem to function.

I resolved this on my end by editing the modules.txt file in the root folder and adding the complete API server launch command with the start_command:
start_command=python server.py --enable-modules=chromadb --listen (in my case, I only want listen and chromadb).

Did I miss something on my end, or is this a problem encountered by others as well? Thank you.

**Comment by deffcolony** [comment]
@Greanibak Yes, I now notice the issue. It occurs right now when you open the launcher.bat for the first time. The script generates a file called `modules.txt` in the current directory where it is being run. You need to modify the modules you wish to enable using the **Edit Extras Modules** option. that is located at: `/ Home / Toolbox / Edit Extras Modules` the start command will work when you activate the modules you want

**Comment by deffcolony** [comment]
@Greanibak 
I've implemented some changes to the launcher.bat script to address the issue you reported. Before closing the issue, could you please let me know if you're still encountering any issues with the modules? otherwise i will close this issue

**Comment by Greanibak** [comment]
Thanks you very much, 
you can close this issue.
