### ISSUE TITLE
[BUG] Unable to download, Getting remote  disconected.

### ISSUE THREAD

**Issue by RyushoYosei** [SillyTavern/SillyTavern-Launcher#32]
### Environment

Windows

### System

Windows

### Describe the problem

Whenever it starts to download, it  just keeps getting cut off remotely.

### Additional info

[12:23:49.67] [INFO] Installing SillyTavern...
[12:23:49.67] [INFO] Cloning SillyTavern repository...
Cloning into 'SillyTavern'...
remote: Enumerating objects: 40885, done.
remote: Counting objects: 100% (3191/3191), done.
remote: Compressing objects: 100% (835/835), done.
error: RPC failed; curl 16 Error in the HTTP2 framing layer/s
error: 7129 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
[12:24:41.71] [INFO] SillyTavern installed successfully.
![image](https://github.com/SillyTavern/SillyTavern-Launcher/assets/53182593/72777d5b-ab09-42ec-bbaa-473a0d93c56a)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern-Launcher/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by RyushoYosei** [comment]
Happens with Git Desktop as well, and normal .git as well, no matter what, "Connection interupted." and refuses to continue, automatically deleting whatever it had gotten, rather then re-checking and continuing like it has any time in the past when I have used git. so All three methods fail. Which is strange because git usually just continues, then verify, doublechecks, finds any errors, downloads the file segments to fix it. But instead it's getting an "End of File" far too early  for some reason.

THis is quite strange, as w hen I used the "Simple launcher" Which is listed as out of date, to not use, it didn't have this issue.

**Comment by deffcolony** [comment]
@RyushoYosei 

Hi, thanksfor the feedback. I'm working on the check system right now, so it will attempt up to three times before returning to the installer menu.
![image](https://github.com/SillyTavern/SillyTavern-Launcher/assets/61471128/4b5b8bb0-42c5-43f3-8eab-b89021eb2d0a)

**Comment by deffcolony** [comment]
@RyushoYosei The feature has been added do a `git pull` or download as zip so it will check now if the git clone gets cloned correctly if not it will retry 3 times

https://github.com/SillyTavern/SillyTavern-Launcher/commit/e0cde01839f664095a4f3adc225a7ca019855e06
