### ISSUE TITLE
[BUG] "The system cannot find the path specified" on opening launcher.bat

### ISSUE THREAD

**Issue by sneed2600** [SillyTavern/SillyTavern-Launcher#39]
### Environment

Windows

### System

Win 11 22H2 build 22621.3007 (current)

### Describe the problem

I installed the launcher as specified in the windows instructions. When I open launcher.bat and type 1, it returns as in the screenshot consistently. Not sure what went on here. The path it shows is the same path that it is installed in. Sorry if this has an obvious fix, I'm not great with this kind of thing.

### Additional info

![Screenshot 2024-03-18 180258](https://github.com/SillyTavern/SillyTavern-Launcher/assets/150194884/b5a19371-0c26-4e6b-8631-31e53c460888)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern-Launcher/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by sneed2600** [comment]
I may have made an embarrassing mistake here and I have fixed it. that was my fault

**Comment by Gerkinfeltser** [comment]
Care to elaborate? I'm having the same issue.
Thanks

**Comment by deffcolony** [comment]
@Gerkinfeltser avoid moving the "SillyTavern" folder outside the "launcher.bat" script directory. This is because the script searches for the "SillyTavern" folder in the same location where you execute the script from.
