### ISSUE TITLE
[BUG] <Failed to activate Conda environment: extras>

### ISSUE THREAD

**Issue by crazyrobinhood** [SillyTavern/SillyTavern-Launcher#41]
### Environment

Linux

### System

Distributor ID:	Pop Description:	Pop!_OS 22.04 LTS Release:	22.04 Codename:	jammy

### Describe the problem

Error during installation of Sillytavern + extras from scratch.

```
/ Installer / SillyTavern + Extras
---------------------------------------------------------------
What is your GPU?
1. NVIDIA
2. AMD
3. None (CPU-only mode)
0. Cancel install

╔════ GPU INFO ═════════════════════════════════════════════════════════════╗
║                                                                           ║
║*  NVIDIA Corporation GA106 [GeForce RTX 3060 Lite Hash Rate] (rev a1)     ║
║                                                                           ║
╚═══════════════════════════════════════════════════════════════════════════╝

Enter the number corresponding to your GPU: 1
[20:20:06] [INFO] GPU choice set to NVIDIA
[20:20:06] [INFO] Installing SillyTavern + Extras...
This may take a while. Please be patient.
[20:20:06] [INFO] Installing SillyTavern...
fatal: destination path 'SillyTavern' already exists and is not an empty directory.
[20:20:06] [INFO] SillyTavern installed successfully.
[20:20:06] [INFO] Installing Extras...
[20:20:06] [INFO] Cloning SillyTavern-extras repository...
fatal: destination path 'SillyTavern-extras' already exists and is not an empty directory.
--2024-03-20 20:20:06--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8303, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 144041912 (137M) [application/octet-stream]
Saving to: ‘/tmp/Miniconda3-latest-Linux-x86_64.sh.1’

Miniconda3-latest-L 100%[===================>] 137.37M  15.3MB/s    in 9.4s    

2024-03-20 20:20:16 (14.7 MB/s) - ‘/tmp/Miniconda3-latest-Linux-x86_64.sh.1’ saved [144041912/144041912]

/tmp/Miniconda3-latest-Linux-x86_64.sh: option requires an argument -- p
ERROR: did not recognize option '?', please try -h
[20:20:16] [INFO] Activating Miniconda environment...
./install.sh: line 379: /etc/profile.d/conda.sh: No such file or directory
[20:20:16] [INFO] Disabling conda auto activate...
./install.sh: line 383: conda: command not found
./install.sh: line 384: conda: command not found
[20:20:16] [INFO] Creating Conda environment extras...
./install.sh: line 387: conda: command not found
[20:20:16] [INFO] Activating Conda environment extras...
./install.sh: line 390: conda: command not found
[20:20:16] [ERROR] Failed to activate Conda environment: extras
[20:20:16] [INFO] Press Enter to try again otherwise close the installer and restart.
Press Enter to try again
```

only option is to press enter and the script just try to download again the miniconda package in /tmp (adding an incremental numeration each time and failing all the time.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern-Launcher/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by ryanzh98** [comment]
facing same issue on windows, environment not created properly. Follow below for workaround

1. conda create --name extras
2. cd to SillyTavern-extras
3. pip install -r requirements.txt (do the same for coqui, rocm, rvc, silicon if needed)
5. run launcher.bat again, if it still giving missing package error may install it one by one by doing pip install [package_name]

**Comment by crazyrobinhood** [comment]
> facing same issue on windows, environment not created properly. Follow below for workaround
> 
>     1. conda create --name extras
> 
>     2. do pip install -r requirements.txt (do the same for coqui, rocm, rvc, silicon if needed)
> 
>     3. run launcher.bat again, if it still giving missing package error may install it one by one by doing pip install [package_name]

Thank you for your reply!
I don't have conda installed in my system. 
No idea on how to install it, there is no such package in the apt source for PoPOS!
Is a conda env a prerequisite?
Shouldn't the script create it by itself?
Thanks in advance!

**Comment by deffcolony** [comment]
@crazyrobinhood Hi could you try again? do `git pull` since i updated the install.sh script

**Comment by crazyrobinhood** [comment]
> @crazyrobinhood Hi could you try again? do `git pull` since i updated the install.sh script

Thanks @deffcolony ! 
Now it seems to go all trough the installing process.
the only errors are  for pyaudio. I'll open another issue.
This one is solved!
