### ISSUE TITLE
Launcher incorrectly reporting VRam

### ISSUE THREAD

**Issue by daddydante88** [SillyTavern/SillyTavern-Launcher#62]
### Environment

🪟 Windows

### System

Windows 11 pro

### Describe the problem

![Untitled](https://github.com/user-attachments/assets/8bc49324-8456-4480-96e8-6abf33b0f406)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
Issue fixed.
Cause: Leftover registry entry from a old GPU
