### ISSUE TITLE
[BUG] alltalk fails to load

### ISSUE THREAD

**Issue by Tom-Neverwinter** [SillyTavern/SillyTavern-Launcher#67]
### Environment

🪟 Windows

### System

windows 10

### Describe the problem

making the inital install the program runs properly.

however on subsequent loads it then has this `error: ModuleNotFoundError: No module named 'requests'`

```
Traceback (most recent call last):
  File "D:\VM\AI\TavernAi\SillyTavern-Launcher\voice-generation\alltalk_tts\script.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

D:\VM\AI\TavernAi\SillyTavern-Launcher\voice-generation\alltalk_tts>

I do not see similar items after taking a quick look and as I have it installed separately in oobabooga this issue only affects silly tavern? maybe related to older requirements vs the beta branch?

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
@Tom-Neverwinter I attempted to replicate the error you mentioned, but after installing ALLTALK in a clean environment, it starts up normally for me. Are you experiencing the same behavior?

https://github.com/user-attachments/assets/1d3ce0ae-c583-4bb5-94ca-357d6665284a
