### ISSUE TITLE
[BUG] Several errors during common installation

### ISSUE THREAD

**Issue by byslexic** [SillyTavern/SillyTavern-Launcher#68]
### Environment

🪟 Windows

### System

win10 v 22H2

### Describe the problem

running installer "git clone https://github.com/SillyTavern/SillyTavern-Launcher.git && cd SillyTavern-Launcher && start installer.bat"
near very end of installation received an error dialog popup, attached(1). The path "T:\AITextGen" is the original installation target. 
After clicking OK, installation finished. 
I selected  #1: Update and start Silly Tavern, which opened a new CMD window and errored out because it could not find Powershell. However, powershell is in use already during installation. 
Selecting option 2 errored out the 1st time with the same error, then a second attempt finally started the server at 127.0.0.1:8000

### Additional info

![Screenshot 2024-08-05 201503](https://github.com/user-attachments/assets/30c1edf8-5df4-4899-ae5b-5a3b8491c8d0)

also 
![Screenshot 2024-08-05 201824](https://github.com/user-attachments/assets/983bbaac-bb72-4479-8d9d-f9e9dcf7342c)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
@byslexic which install option did you choose from the installer.bat?

**Comment by byslexic** [comment]
> @byslexic which install option did you choose from the installer.bat?

I believe it was "Install All". I wanted to install ST, Extras, TTS, and whatever else.

**Comment by byslexic** [comment]
Further issues:
using SillyTavern Launcher opion1 Update & start,  error with Powershell appears essentially the same as screenshot #2 above, and then the Launcher window shows 
```
[ERROR] Log file not found, something went wrong. Close all SillyTavern command windows and try again.
Press any key to continue . . .
```
"Continuing" comes back to main Launcher options. 
Selecting optn 2 Start SillyTavern again opens a cmd window, ending with the message ```

83 packages are looking for funding
  run `npm fund` for details
Starting Node.js server with command: node server.js
'powershell' is not recognized as an internal or external command,
operable program or batch file.
Node.js server started.
Press any key to continue . . .
```
However after 30 seconds ST starts anyway. 
The Extensions menu in ST show that the ST Extras are not connected/ Extras API does not start.

**Comment by deffcolony** [comment]
@byslexic i have one way to make powershell work in windows so try this

1. run the following command in CMD:
```bat
winget install -e --id Microsoft.PowerShell
```

2. Run this command in CMD to edit environment variables
```bat
start "" rundll32.exe sysdm.cpl,EditEnvironmentVariables
```

3. add the following lines in the user PATH
`C:\Windows\System32\WindowsPowerShell\v1.0`
`C:\WINDOWS\System32\WindowsPowerShell\v1.0`

![image](https://github.com/user-attachments/assets/6cfee8cf-7772-4254-a02b-76eec4789647)

4. Now start the launcher again and see if it can see powershell now

**Comment by byslexic** [comment]
Thank you @deffcolony, that solved the error. I think it's odd that other parts of Silly Tavern had no problem starting and using powershell, but I can't claim to understand why. 
There are other errors that still happen with the launcher that I will submit under their own issues.
