### ISSUE TITLE
[BUG] Launcher doesnt account for koboldcpp_rocm.exe

### ISSUE THREAD

**Issue by BarryOConnor** [SillyTavern/SillyTavern-Launcher#73]
### Environment

🪟 Windows

### System

Windows 11 V23H2

### Describe the problem

If you use the Launcher Toolbox options to install or update KoboldCPP and you choose AMD GPU, it correctly installs the koboldcpp_rocm.exe version.  However, neither the toolbox launcher or the custom shortcut account for this and both just try and run koboldcpp.exe causing an error popup to appear.

Unlike the Install/Update sections of the Launcher code, the following never checks which version to run
```
:start_koboldcpp
REM Start koboldcpp with desired configurations
echo %blue_bg%[%time%]%reset% %blue_fg_strong%[INFO]%reset% koboldcpp launched in a new window.

cd /d "%koboldcpp_install_path%"
start "" "koboldcpp.exe"
goto :home
```

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
@BarryOConnor I fixed the launch bug for koboldcpp amd version please update the launcher (by restarting it)

https://github.com/SillyTavern/SillyTavern-Launcher/commit/e357d81cdecbd1bda0496ff8d6ecd739fce60d19

**Comment by BarryOConnor** [comment]
Yep, all working.  Thanks for the quick fix!
