### ISSUE TITLE
[BUG] Launcher is not setting the NODE_ENV environment variable.

### ISSUE THREAD

**Issue by Cohee1207** [SillyTavern/SillyTavern-Launcher#77]
### Environment

🪟 Windows

### System

Any Windows

### Describe the problem

The startup scripts in the main repo set the NODE_ENV to production.
https://github.com/SillyTavern/SillyTavern/blob/5a4e23f62f12d3b91d01d261d52a3e78abff8492/Start.bat#L3

This doesn't happen when using the launcher.

### Additional info

Why is it bad?

1. The server will report as running in an undefined environment upon startup.
2. Some libraries may not include additional optimizations that are only activated in production.

How to fix?

Add `set NODE_ENV=production` at the very start of the launcher.bat or in the server startup string.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
this issue has now been fixed at

https://github.com/SillyTavern/SillyTavern-Launcher/commit/3c6bca60065e3fd69faad98e51ffd292689e1414#diff-a0205db631f5d0cd7cb7ccd40570bf1addb891e7775d7aa8cba136ee3b30834dR21
and 
https://github.com/SillyTavern/SillyTavern-Launcher/commit/a07fa2eea096dc455b1e0df2eab71d8598860ad8
