### ISSUE TITLE
[BUG] Unable to Launch After New Version Update

### ISSUE THREAD

**Issue by moonslashx** [SillyTavern/SillyTavern-Launcher#82]
### Environment

🪟 Windows

### System

Version 23H2

### Describe the problem

When tapping the Silly Tavern shortcut or when launching from the launcher the command window shows as npm Install and nothing happens. No errors appear, no text appears, it just sits there and does nothing when previously to updating it worked fine.

### Additional info

I've uninstalled and reinstalled, tried tapping through various troubleshooting options but nothing has fixed or changed it.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
@moonslashx Why did you close the issue? was it already solved?

**Comment by moonslashx** [comment]
> @moonslashx Why did you close the issue? was it already solved?

The issue was my virus blocker for some reason.  Fixed the issue and it works now.
