### ISSUE TITLE
[BUG] invokeai-web launcher is wrong

### ISSUE THREAD

**Issue by AveryVeilfaire** [SillyTavern/SillyTavern-Launcher#91]
### Environment

🪟 Windows

### System

Windows

### Describe the problem

The bat for invokeai-web needs to include the invokeai dir when run

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by deffcolony** [comment]
@AveryVeilfaire This is now fixed at https://github.com/SillyTavern/SillyTavern-Launcher/commit/3cee65e6bdd5e3e834a90e816d3e8cb1ab2d2892 Please update the launcher. The invokeai should now launch correctly
